"""Tool-using agent for adjudicating uncertain MONDO disease matches."""

from typing import Literal

from agents import Agent, function_tool
from pydantic import BaseModel, Field

from lib.agents.base_instructions import BASE_SYSTEM_INSTRUCTIONS
from lib.core.environment import env
from lib.models.evidence_block import ReasoningBlock
from lib.reference_data import mondo


class MondoAgentDecision(BaseModel):
    mondo_id: str | None = Field(
        default=None,
        description='Selected MONDO identifier, or null when no supported match exists.',
    )
    term: str | None = Field(
        default=None,
        description='Selected MONDO label, or null when no supported match exists.',
    )
    confidence: Literal['high', 'medium', 'low'] | None = None
    match_type: mondo.MondoMatchType | None = None


@function_tool
def search_mondo_terms(
    query: str,
    limit: int = 20,
) -> list[dict]:
    """Search MONDO aliases and return reranked candidate terms."""
    fuzzy_candidates = mondo.retrieve_mondo_fuzzy_candidates(
        mondo.get_mondo_index(),
        query,
        limit=limit,
    )
    return [candidate.model_dump() for candidate in fuzzy_candidates]


@function_tool
def get_mondo_term(mondo_id: str) -> dict:
    """Fetch MONDO term information."""
    term = mondo.get_mondo_term(mondo_id)
    if term is None:
        raise ValueError(f'MONDO term {mondo_id} not found')
    return term


@function_tool
def get_mondo_parents(mondo_id: str) -> list[dict]:
    """Fetch parent terms for a MONDO term."""
    return mondo.get_mondo_related_terms(mondo_id, 'parents')


@function_tool
def get_mondo_children(mondo_id: str) -> list[dict]:
    """Fetch child terms for a MONDO term."""
    return mondo.get_mondo_related_terms(mondo_id, 'children')


@function_tool
def get_mondo_by_xref(identifier: str) -> list[dict]:
    """Fetch MONDO terms by external identifier."""
    return mondo.get_mondo_terms_by_xref(identifier)


INSTRUCTIONS = """
You are an expert at mapping clinical disease descriptions to MONDO terms.

Fuzzy candidate terms were generated by RapidFuzz after deterministic exact
lookup did not find a unique match. Similarity scores are retrieval signals
only; use term meaning, definitions, aliases, xrefs, hierarchy, and the supplied
paper context to decide whether a supported MONDO match exists.

Return exactly one MondoAgentDecision.

Rules:
- Never invent a MONDO ID.
- Select only a term returned by the fuzzy candidates or by tools.
- Prefer null over a weak guess.
- Use paper context only to disambiguate supported candidates, not to infer
  unsupported disease specificity.
- Before selecting a term, call get_mondo_term() to verify it exists and inspect
  its label, definition, aliases, and xrefs.
- If no fuzzy candidate is suitable, use search_mondo_terms() with alternative
  spellings, abbreviations, or clinically equivalent wording.
- Use get_mondo_parents() or get_mondo_children() when specificity is unclear.
- Use get_mondo_by_xref() when the disease string or context includes an
  external identifier such as OMIM, Orphanet, GARD, MedGen, MeSH, or ICD.

Decision guidance:
- Prefer exact labels and exact synonyms when they match the disease meaning.
- Prefer more specific MONDO terms only when the input text or context supports
  that specificity.
- Reject candidates that match only a generic token such as "disease" or
  "syndrome".
- For apparent misspellings, select the closest supported candidate only when
  the intended disease is clear.
- For ambiguous abbreviations, return null unless context or tools clearly
  resolve the abbreviation.

Output:
{
  "mondo_id": "MONDO:0000000" or null,
  "term": "label" or null,
  "confidence": "high" | "medium" | "low" | null,
  "match_type": "agent_selected" | "primary_label" | "exact_synonym" |
    "related_synonym" | "xref" | "exact_mapping_id" |
    "hasBroadSynonym" | "hasNarrowSynonym" | "abbreviation" |
    "deprecated_replacement" | null
}
"""

MONDO_LINKING_AGENT_INSTRUCTIONS = INSTRUCTIONS

agent = Agent(
    name='mondo_linker',
    instructions=BASE_SYSTEM_INSTRUCTIONS,
    model=env.OPENAI_API_DEPLOYMENT,
    output_type=ReasoningBlock[MondoAgentDecision],
    tools=[
        search_mondo_terms,
        get_mondo_term,
        get_mondo_parents,
        get_mondo_children,
        get_mondo_by_xref,
    ],
)
