"""refactor patient model with split value and evidence columns

Revision ID: 01f89ca46c4c
Revises: a111864ea9d9
Create Date: 2026-03-19 19:52:11.514120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01f89ca46c4c'
down_revision: Union[str, None] = 'a111864ea9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier_evidence', sa.JSON(), nullable=False))
        batch_op.add_column(
            sa.Column('proband_status_evidence', sa.JSON(), nullable=False)
        )
        batch_op.add_column(sa.Column('sex_evidence', sa.JSON(), nullable=False))
        batch_op.add_column(
            sa.Column('age_diagnosis_evidence', sa.JSON(), nullable=False)
        )
        batch_op.add_column(sa.Column('age_report_evidence', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('age_death_evidence', sa.JSON(), nullable=False))
        batch_op.add_column(
            sa.Column('country_of_origin_evidence', sa.JSON(), nullable=False)
        )
        batch_op.add_column(
            sa.Column('race_ethnicity_evidence', sa.JSON(), nullable=False)
        )
        batch_op.add_column(
            sa.Column('affected_status_evidence', sa.JSON(), nullable=False)
        )
        batch_op.alter_column(
            'identifier',
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'proband_status',
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'sex', existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            'age_diagnosis',
            existing_type=sa.TEXT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'age_report',
            existing_type=sa.TEXT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'age_death',
            existing_type=sa.TEXT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'country_of_origin',
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'race_ethnicity',
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'affected_status',
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f('ix_patients_paper_id_identifier'))
        batch_op.drop_column('proband_status_reasoning')
        batch_op.drop_column('age_diagnosis_evidence_context')
        batch_op.drop_column('affected_status_evidence_context')
        batch_op.drop_column('race_ethnicity_evidence_context')
        batch_op.drop_column('affected_status_reasoning')
        batch_op.drop_column('race_ethnicity_reasoning')
        batch_op.drop_column('proband_status_evidence_context')
        batch_op.drop_column('age_diagnosis_reasoning')
        batch_op.drop_column('sex_reasoning')
        batch_op.drop_column('identifier_reasoning')
        batch_op.drop_column('age_death_reasoning')
        batch_op.drop_column('country_of_origin_evidence_context')
        batch_op.drop_column('age_report_evidence_context')
        batch_op.drop_column('age_death_evidence_context')
        batch_op.drop_column('country_of_origin_reasoning')
        batch_op.drop_column('age_report_reasoning')
        batch_op.drop_column('sex_evidence_context')
        batch_op.drop_column('identifier_evidence_context')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('identifier_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(sa.Column('sex_evidence_context', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('age_report_reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column('country_of_origin_reasoning', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('age_death_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('age_report_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('country_of_origin_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(sa.Column('age_death_reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('identifier_reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sex_reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column('age_diagnosis_reasoning', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('proband_status_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('race_ethnicity_reasoning', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('affected_status_reasoning', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('race_ethnicity_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('affected_status_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('age_diagnosis_evidence_context', sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('proband_status_reasoning', sa.TEXT(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f('ix_patients_paper_id_identifier'),
            ['paper_id', 'identifier'],
            unique=False,
        )
        batch_op.alter_column(
            'affected_status',
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'race_ethnicity',
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'country_of_origin',
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'age_death',
            existing_type=sa.Integer(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'age_report',
            existing_type=sa.Integer(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'age_diagnosis',
            existing_type=sa.Integer(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'sex', existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            'proband_status',
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'identifier',
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.drop_column('affected_status_evidence')
        batch_op.drop_column('race_ethnicity_evidence')
        batch_op.drop_column('country_of_origin_evidence')
        batch_op.drop_column('age_death_evidence')
        batch_op.drop_column('age_report_evidence')
        batch_op.drop_column('age_diagnosis_evidence')
        batch_op.drop_column('sex_evidence')
        batch_op.drop_column('proband_status_evidence')
        batch_op.drop_column('identifier_evidence')

    # ### end Alembic commands ###
