"""baseline genes and papers tables

Revision ID: 05a3d6bb98ed
Revises: 
Create Date: 2026-03-03 15:22:50.255083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a3d6bb98ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genes_symbol'), ['symbol'], unique=True)

    op.create_table('papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('pipeline_status', sa.Enum('QUEUED', 'EXTRACTION_RUNNING', 'EXTRACTION_FAILED', 'EXTRACTION_COMPLETED', 'LINKING_RUNNING', 'LINKING_FAILED', 'COMPLETED', name='pipelinestatus'), server_default='Queued', nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_gene_id'), ['gene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_last_modified'), ['last_modified'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_last_modified'))
        batch_op.drop_index(batch_op.f('ix_papers_id'))
        batch_op.drop_index(batch_op.f('ix_papers_gene_id'))
        batch_op.drop_index(batch_op.f('ix_papers_filename'))

    op.drop_table('papers')
    with op.batch_alter_table('genes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genes_symbol'))

    op.drop_table('genes')
    # ### end Alembic commands ###
