"""add deletion_log table

Revision ID: 08d2ca5ef811
Revises: 41ca6d53799a
Create Date: 2026-09-21 17:51:35.501993

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08d2ca5ef811'
down_revision: Union[str, None] = '41ca6d53799a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deletion_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.Integer(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('identifier_snapshot', sa.Text(), nullable=True),
        sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
        sa.Column(
            'deleted_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('deletion_log', schema=None) as batch_op:
        batch_op.create_index('ix_deletion_log_paper_id', ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_log', schema=None) as batch_op:
        batch_op.drop_index('ix_deletion_log_paper_id')

    op.drop_table('deletion_log')
    # ### end Alembic commands ###
