"""rename enriched_variants to annotated_variants (autogenerated)

Revision ID: 139e89a5eb03
Revises: l2m3n4o5p6q7
Create Date: 2026-05-24 23:53:00.513208

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '139e89a5eb03'
down_revision: Union[str, None] = 'l2m3n4o5p6q7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('annotated_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enriched_variants_variant_id'))
        batch_op.drop_constraint(
            batch_op.f('uq_enriched_variants_variant_id'), type_='unique'
        )
        batch_op.create_index(
            'ix_annotated_variants_variant_id', ['variant_id'], unique=False
        )
        batch_op.create_unique_constraint(
            'uq_annotated_variants_variant_id', ['variant_id']
        )


def downgrade() -> None:
    with op.batch_alter_table('annotated_variants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_annotated_variants_variant_id', type_='unique')
        batch_op.drop_index('ix_annotated_variants_variant_id')
        batch_op.create_unique_constraint(
            batch_op.f('uq_enriched_variants_variant_id'), ['variant_id']
        )
        batch_op.create_index(
            batch_op.f('ix_enriched_variants_variant_id'), ['variant_id'], unique=False
        )
