"""rename enriched_variants to annotated_variants (autogenerated)

Revision ID: 139e89a5eb03
Revises: l2m3n4o5p6q7
Create Date: 2026-05-24 23:53:00.513208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '139e89a5eb03'
down_revision: Union[str, None] = 'l2m3n4o5p6q7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phenotypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('concept_evidence', sa.JSON(), nullable=False),
    sa.Column('negated', sa.Boolean(), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('family_history', sa.Boolean(), nullable=False),
    sa.Column('onset', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phenotypes', schema=None) as batch_op:
        batch_op.create_index('ix_phenotypes_paper_id', ['paper_id'], unique=False)
        batch_op.create_index('ix_phenotypes_patient_id', ['patient_id'], unique=False)

    op.create_table('hpos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phenotype_id', sa.Integer(), nullable=False),
    sa.Column('hpo_id', sa.String(), nullable=True),
    sa.Column('hpo_name', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phenotype_id'], ['phenotypes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phenotype_id', name='uq_hpos_phenotype_id')
    )
    op.drop_table('_alembic_tmp_papers')
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('annotated_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enriched_variants_variant_id'))
        batch_op.drop_constraint(batch_op.f('uq_enriched_variants_variant_id'), type_='unique')
        batch_op.create_index('ix_annotated_variants_variant_id', ['variant_id'], unique=False)
        batch_op.create_unique_constraint('uq_annotated_variants_variant_id', ['variant_id'])

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('tag')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'agent_runs', ['agent_run_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=13), nullable=True))

    with op.batch_alter_table('annotated_variants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_annotated_variants_variant_id', type_='unique')
        batch_op.drop_index('ix_annotated_variants_variant_id')
        batch_op.create_unique_constraint(batch_op.f('uq_enriched_variants_variant_id'), ['variant_id'])
        batch_op.create_index(batch_op.f('ix_enriched_variants_variant_id'), ['variant_id'], unique=False)

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('_alembic_tmp_patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paper_id', sa.INTEGER(), nullable=False),
    sa.Column('family_id', sa.INTEGER(), nullable=False),
    sa.Column('identifier', sa.VARCHAR(), nullable=False),
    sa.Column('proband_status', sa.VARCHAR(), nullable=False),
    sa.Column('sex', sa.VARCHAR(), nullable=False),
    sa.Column('age_diagnosis', sa.INTEGER(), nullable=True),
    sa.Column('age_report', sa.INTEGER(), nullable=True),
    sa.Column('age_death', sa.INTEGER(), nullable=True),
    sa.Column('country_of_origin', sa.VARCHAR(), nullable=False),
    sa.Column('race_ethnicity', sa.VARCHAR(), nullable=False),
    sa.Column('affected_status', sa.VARCHAR(), nullable=False),
    sa.Column('identifier_evidence', sqlite.JSON(), nullable=False),
    sa.Column('proband_status_evidence', sqlite.JSON(), nullable=False),
    sa.Column('sex_evidence', sqlite.JSON(), nullable=False),
    sa.Column('age_diagnosis_evidence', sqlite.JSON(), nullable=False),
    sa.Column('age_report_evidence', sqlite.JSON(), nullable=False),
    sa.Column('age_death_evidence', sqlite.JSON(), nullable=False),
    sa.Column('country_of_origin_evidence', sqlite.JSON(), nullable=False),
    sa.Column('race_ethnicity_evidence', sqlite.JSON(), nullable=False),
    sa.Column('affected_status_evidence', sqlite.JSON(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('age_diagnosis_unit', sa.VARCHAR(length=6), nullable=True),
    sa.Column('age_report_unit', sa.VARCHAR(length=6), nullable=True),
    sa.Column('age_death_unit', sa.VARCHAR(length=6), nullable=True),
    sa.Column('family_assignment_evidence', sqlite.JSON(), nullable=False),
    sa.Column('is_obligate_carrier', sa.BOOLEAN(), nullable=True),
    sa.Column('relationship_to_proband', sa.VARCHAR(), nullable=True),
    sa.Column('twin_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_obligate_carrier_evidence', sqlite.JSON(), nullable=True),
    sa.Column('relationship_to_proband_evidence', sqlite.JSON(), nullable=True),
    sa.Column('twin_type_evidence', sqlite.JSON(), nullable=True),
    sa.Column('agent_run_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_patients_agent_run_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(), nullable=False),
    sa.Column('gene_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('first_author', sa.VARCHAR(), nullable=True),
    sa.Column('journal_name', sa.VARCHAR(), nullable=True),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('publication_year', sa.INTEGER(), nullable=True),
    sa.Column('doi', sa.VARCHAR(), nullable=True),
    sa.Column('pmid', sa.VARCHAR(), nullable=True),
    sa.Column('pmcid', sa.VARCHAR(), nullable=True),
    sa.Column('paper_types', sqlite.JSON(), nullable=False),
    sa.Column('supplement_format', sa.VARCHAR(length=4), nullable=True),
    sa.Column('is_paper_relevant', sa.BOOLEAN(), nullable=True),
    sa.Column('section_classifications', sqlite.JSON(), nullable=True),
    sa.Column('disease_name', sa.VARCHAR(), nullable=True),
    sa.Column('disease_name_evidence', sqlite.JSON(), nullable=True),
    sa.Column('disease_inheritance_mode', sa.VARCHAR(), nullable=True),
    sa.Column('disease_inheritance_mode_evidence', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hpos')
    with op.batch_alter_table('phenotypes', schema=None) as batch_op:
        batch_op.drop_index('ix_phenotypes_patient_id')
        batch_op.drop_index('ix_phenotypes_paper_id')

    op.drop_table('phenotypes')
    # ### end Alembic commands ###
