"""add supplement_format to papers

Revision ID: 170ae36b1b74
Revises: 22d031751279
Create Date: 2026-05-08 19:53:29.387720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170ae36b1b74'
down_revision: Union[str, None] = '22d031751279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplement_format', sa.Enum('PDF', 'DOCX', name='fileformat'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('supplement_format')

    # ### end Alembic commands ###
