"""add segregation evidence/computed tables and family_id to tasks

Revision ID: 22d031751279
Revises: a2f3b4c5d6e7
Create Date: 2026-04-22 14:13:18.727162

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '22d031751279'
down_revision: Union[str, None] = 'a2f3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'segregation_analysis_computed',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('segregation_count', sa.Integer(), nullable=False),
        sa.Column('segregation_count_reasoning', sa.JSON(), nullable=False),
        sa.Column('computed_lod_score', sa.Float(), nullable=False),
        sa.Column('computed_lod_score_reasoning', sa.JSON(), nullable=False),
        sa.Column('points_assigned', sa.Float(), nullable=False),
        sa.Column('points_assigned_reasoning', sa.JSON(), nullable=False),
        sa.Column('meets_minimum_criteria', sa.Boolean(), nullable=False),
        sa.Column('meets_minimum_criteria_reasoning', sa.JSON(), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('segregation_analysis_computed', schema=None) as batch_op:
        batch_op.create_index(
            'ix_segregation_analysis_computed_family_id', ['family_id'], unique=False
        )

    op.create_table(
        'segregation_evidence',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('extracted_lod_score', sa.Float(), nullable=True),
        sa.Column('extracted_lod_score_evidence', sa.JSON(), nullable=True),
        sa.Column('sequencing_methodology', sa.String(), nullable=False),
        sa.Column('sequencing_methodology_evidence', sa.JSON(), nullable=False),
        sa.Column('has_unexplainable_non_segregations', sa.Boolean(), nullable=False),
        sa.Column(
            'has_unexplainable_non_segregations_evidence', sa.JSON(), nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('segregation_evidence', schema=None) as batch_op:
        batch_op.create_index(
            'ix_segregation_evidence_family_id', ['family_id'], unique=False
        )

    with op.batch_alter_table('segregation_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segregation_analyses_family_id'))

    op.drop_table('segregation_analyses')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.alter_column(
            'type',
            existing_type=sa.VARCHAR(length=23),
            type_=sa.Enum(
                'PDF_PARSING',
                'PAPER_METADATA',
                'VARIANT_EXTRACTION',
                'PEDIGREE_DESCRIPTION',
                'PATIENT_EXTRACTION',
                'SEGREGATION_EVIDENCE_EXTRACTION',
                'SEGREGATION_ANALYSIS_COMPUTED',
                'VARIANT_HARMONIZATION',
                'VARIANT_ENRICHMENT',
                'PATIENT_VARIANT_LINKING',
                'PHENOTYPE_EXTRACTION',
                'HPO_LINKING',
                name='tasktype',
            ),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f('ix_tasks_dedup'))
        batch_op.create_index(
            'ix_tasks_dedup',
            [
                'type',
                'paper_id',
                'family_id',
                'patient_id',
                'variant_id',
                'phenotype_id',
            ],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f('ix_tasks_family_id'), ['family_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_tasks_family_id', 'families', ['family_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('scoring_method')
        batch_op.drop_column('scoring_method_evidence')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_family_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_family_id'))
        batch_op.drop_index('ix_tasks_dedup')
        batch_op.create_index(
            batch_op.f('ix_tasks_dedup'),
            ['type', 'paper_id', 'patient_id', 'variant_id', 'phenotype_id'],
            unique=1,
        )
        batch_op.alter_column(
            'type',
            existing_type=sa.Enum(
                'PDF_PARSING',
                'PAPER_METADATA',
                'VARIANT_EXTRACTION',
                'PEDIGREE_DESCRIPTION',
                'PATIENT_EXTRACTION',
                'SEGREGATION_EVIDENCE_EXTRACTION',
                'SEGREGATION_ANALYSIS_COMPUTED',
                'VARIANT_HARMONIZATION',
                'VARIANT_ENRICHMENT',
                'PATIENT_VARIANT_LINKING',
                'PHENOTYPE_EXTRACTION',
                'HPO_LINKING',
                name='tasktype',
            ),
            type_=sa.VARCHAR(length=23),
            existing_nullable=False,
        )
        batch_op.drop_column('family_id')

    op.create_table(
        'segregation_analyses',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('family_id', sa.INTEGER(), nullable=False),
        sa.Column('segregation_count', sa.INTEGER(), nullable=False),
        sa.Column('lod_score', sa.FLOAT(), nullable=False),
        sa.Column('lod_score_type', sa.VARCHAR(length=9), nullable=False),
        sa.Column('sequencing_methodology', sa.VARCHAR(), nullable=False),
        sa.Column('points_assigned', sa.FLOAT(), nullable=False),
        sa.Column('meets_minimum_criteria', sa.BOOLEAN(), nullable=False),
        sa.Column('has_unexplainable_non_segregations', sa.BOOLEAN(), nullable=False),
        sa.Column('segregation_count_evidence', sqlite.JSON(), nullable=False),
        sa.Column('lod_score_evidence', sqlite.JSON(), nullable=False),
        sa.Column('lod_score_type_evidence', sqlite.JSON(), nullable=False),
        sa.Column('sequencing_methodology_evidence', sqlite.JSON(), nullable=False),
        sa.Column('points_assigned_evidence', sqlite.JSON(), nullable=False),
        sa.Column('meets_minimum_criteria_evidence', sqlite.JSON(), nullable=False),
        sa.Column(
            'has_unexplainable_non_segregations_evidence', sqlite.JSON(), nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DATETIME(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('segregation_analyses', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_segregation_analyses_family_id'), ['family_id'], unique=False
        )

    with op.batch_alter_table('segregation_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_segregation_evidence_family_id')

    op.drop_table('segregation_evidence')
    with op.batch_alter_table('segregation_analysis_computed', schema=None) as batch_op:
        batch_op.drop_index('ix_segregation_analysis_computed_family_id')

    op.drop_table('segregation_analysis_computed')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_method', sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column('scoring_method_evidence', sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###
