"""add manually_linked to hpos

Revision ID: 24be132ecd9b
Revises: 08d2ca5ef811
Create Date: 2026-09-21 21:46:15.875704

Hand-edited away from the autogenerated form, which wrapped this in
batch_alter_table. Not needed here: this is a plain ADD COLUMN, which SQLite
performs in place, and `hpos` has no CASCADE dependents anyway. Adding a NOT
NULL column is legal because it carries a server_default, which backfills
existing rows -- see the migration-safety section of CLAUDE.md and
cab7e60ebd9f for the same pattern.

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24be132ecd9b'
down_revision: Union[str, None] = '08d2ca5ef811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Every existing hpos row was produced by extraction, so backfilling
    # false is correct for all of them.
    op.add_column(
        'hpos',
        sa.Column(
            'manually_linked',
            sa.Boolean(),
            server_default='0',
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column('hpos', 'manually_linked')
