"""add skip_successors to tasks

Revision ID: 2572a7910764
Revises: 4cbb2b527fde
Create Date: 2026-04-08 22:36:24.001756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2572a7910764'
down_revision: Union[str, None] = '4cbb2b527fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'skip_successors', sa.Boolean(), server_default='0', nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('skip_successors')

    # ### end Alembic commands ###
