"""add foreign key constraint for patient relationship in extracted_phenotypes

Revision ID: 26e1efd53c70
Revises: 59e9bc9ffddb
Create Date: 2026-03-24 16:48:49.129648

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26e1efd53c70'
down_revision: Union[str, None] = '59e9bc9ffddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_extracted_phenotypes_patients',
            'patients',
            ['paper_id', 'patient_idx'],
            ['paper_id', 'patient_idx'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_extracted_phenotypes_patients', type_='foreignkey')

    # ### end Alembic commands ###
