"""make_conversation_id_nullable

Revision ID: 2c82db2f13fe
Revises: d661f629ece9
Create Date: 2026-05-17 21:37:48.510814

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c82db2f13fe'
down_revision: Union[str, None] = 'd661f629ece9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column(
            'conversation_id', existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column(
            'conversation_id', existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
