"""add consanguinity to families

Revision ID: 3b2d941d02a2
Revises: 3ba072e85738
Create Date: 2026-06-04 11:47:36.901792

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b2d941d02a2'
down_revision: Union[str, None] = '3ba072e85738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consanguinity', sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column('consanguinity_evidence', sa.JSON(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('consanguinity_evidence')
        batch_op.drop_column('consanguinity')

    # ### end Alembic commands ###
