"""split paired_variant_confidence and reasoning

Revision ID: 3ba072e85738
Revises: cabffa6b7543
Create Date: 2026-06-03 10:20:17.023123

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3ba072e85738'
down_revision: Union[str, None] = 'cabffa6b7543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_occurrences', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('paired_variant_confidence', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('paired_variant_confidence_reasoning', sa.JSON(), nullable=True)
        )
        batch_op.drop_column('paired_variant_link_reasoning')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_occurrences', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('paired_variant_link_reasoning', sqlite.JSON(), nullable=True)
        )
        batch_op.drop_column('paired_variant_confidence_reasoning')
        batch_op.drop_column('paired_variant_confidence')

    # ### end Alembic commands ###
