"""drop redundant new_value column from edits

Revision ID: 41ca6d53799a
Revises: 9aa984af2f96
Create Date: 2026-09-21 17:06:56.214751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ca6d53799a'
down_revision: Union[str, None] = '9aa984af2f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.drop_column('new_value')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_value', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
