"""add family assignment evidence to patients

Revision ID: 4cbb2b527fde
Revises: d09d0a5680a8
Create Date: 2026-04-08 15:35:49.613180

"""

from typing import Sequence, Union
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbb2b527fde'
down_revision: Union[str, None] = 'd09d0a5680a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('family_assignment_evidence', sa.JSON(), nullable=True)
        )

    # Populate existing rows with dummy evidence
    connection = op.get_bind()
    dummy_evidence = json.dumps(
        {
            'value': 'Unknown',
            'reasoning': 'Auto-populated during migration',
        }
    )
    connection.execute(
        sa.text(
            f'UPDATE patients SET family_assignment_evidence = :evidence WHERE family_assignment_evidence IS NULL'
        ),
        {'evidence': dummy_evidence},
    )

    # Make column NOT NULL
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('family_assignment_evidence', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('family_assignment_evidence')

    # ### end Alembic commands ###
