"""drop tasks.run_id

Revision ID: 4cd141cb67ae
Revises: 24be132ecd9b
Create Date: 2026-09-23 01:00:13.060762

Superseded by predecessor-gated local completion (a task type's progress can
now be read straight off its own rows' status), and its only other consumers
-- the per-run historical duration stats and snapshot metadata -- are removed
in this same change. A plain column+index drop: `tasks` is only ever the
child in its FK relationships, so no CASCADE dependent can be affected and
none of CLAUDE.md's PRAGMA-foreign-keys-off batch-alter dance is needed.

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cd141cb67ae'
down_revision: Union[str, None] = '24be132ecd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_run_id'))
        batch_op.drop_column('run_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###
