"""add_segregation_analyses_table

Revision ID: 4d0f368e0b7a
Revises: 7f8c9d3e5a2b
Create Date: 2026-04-21 20:39:36.452731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0f368e0b7a'
down_revision: Union[str, None] = '7f8c9d3e5a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_method_evidence', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('scoring_method_evidence')

    # ### end Alembic commands ###
