"""add paper extraction metadata columns

Revision ID: 4d8d51219fe1
Revises: 05a3d6bb98ed
Create Date: 2026-03-03 15:24:32.942011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8d51219fe1'
down_revision: Union[str, None] = '05a3d6bb98ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pmid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pmcid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('doi', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('abstract', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('journal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_author', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pub_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper_types', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('paper_types')
        batch_op.drop_column('pub_year')
        batch_op.drop_column('first_author')
        batch_op.drop_column('journal')
        batch_op.drop_column('abstract')
        batch_op.drop_column('title')
        batch_op.drop_column('doi')
        batch_op.drop_column('pmcid')
        batch_op.drop_column('pmid')

    # ### end Alembic commands ###
