"""add segregation analyses and scoring method evidence

Revision ID: 4ffa1c66601b
Revises: 7f8c9d3e5a2b
Create Date: 2026-04-21 20:39:36.452731

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ffa1c66601b'
down_revision: Union[str, None] = '7f8c9d3e5a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'segregation_analyses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('segregation_count', sa.Integer(), nullable=False),
        sa.Column('lod_score', sa.Float(), nullable=False),
        sa.Column('lod_score_type', sa.String(), nullable=False),
        sa.Column('sequencing_methodology', sa.String(), nullable=False),
        sa.Column('points_assigned', sa.Float(), nullable=False),
        sa.Column('meets_minimum_criteria', sa.Boolean(), nullable=False),
        sa.Column('has_unexplainable_non_segregations', sa.Boolean(), nullable=False),
        sa.Column('analysis_notes', sa.String(), nullable=False),
        sa.Column('segregation_count_evidence', sa.JSON(), nullable=False),
        sa.Column('lod_score_evidence', sa.JSON(), nullable=False),
        sa.Column('lod_score_type_evidence', sa.JSON(), nullable=False),
        sa.Column('sequencing_methodology_evidence', sa.JSON(), nullable=False),
        sa.Column('points_assigned_evidence', sa.JSON(), nullable=False),
        sa.Column('meets_minimum_criteria_evidence', sa.JSON(), nullable=False),
        sa.Column(
            'has_unexplainable_non_segregations_evidence', sa.JSON(), nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('segregation_analyses', schema=None) as batch_op:
        batch_op.create_index(
            'ix_segregation_analyses_family_id', ['family_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segregation_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_segregation_analyses_family_id')

    op.drop_table('segregation_analyses')

    # ### end Alembic commands ###
