"""add scoring_method and scoring_method_evidence to papers

Revision ID: 50d7e319ffa3
Revises: c3e1ecc3aa06
Create Date: 2026-04-21 15:54:53.368689

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50d7e319ffa3'
down_revision: Union[str, None] = 'c3e1ecc3aa06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_method', sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column('scoring_method_evidence', sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('scoring_method')
        batch_op.drop_column('scoring_method_evidence')

    # ### end Alembic commands ###
