"""add user avatar_updated_at

Written by hand rather than autogenerated, for the reason cab7e60ebd9f records:
autogenerate wraps ADD COLUMN in batch_alter_table, which on SQLite copies the
table, drops the original and renames the copy. `users` is the parent of CASCADE
foreign keys (tasks.updated_by_user_id among them), which is the shape that
emptied the patients table in 3b2d941d02a2. See the migration-safety section of
CLAUDE.md.

A plain op.add_column is all this needs -- SQLite adds a nullable column in
place, with no table rewrite and so no CASCADE exposure.

Revision ID: 5767de58a19b
Revises: cab7e60ebd9f
Create Date: 2026-09-10 23:40:42.012300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5767de58a19b'
down_revision: Union[str, None] = 'cab7e60ebd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable, and NULL means "no avatar" -- correct for every existing user,
    # none of whom has one. A timestamp rather than a boolean because it also
    # cache-busts the avatar URL, whose path is otherwise stable.
    op.add_column(
        'users',
        sa.Column('avatar_updated_at', sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    # Image files under {CAA_ROOT}/avatars/ are deliberately left in place: a
    # downgrade should not destroy user data that a re-upgrade would surface
    # again.
    op.drop_column('users', 'avatar_updated_at')
