"""standardize timestamps to updated_at only

Revision ID: 59e9bc9ffddb
Revises: d5f3a9c2b1e4
Create Date: 2026-03-24 15:33:41.016509

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '59e9bc9ffddb'
down_revision: Union[str, None] = 'd5f3a9c2b1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phenotype_idx', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('concept', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('concept_evidence', sa.JSON(), nullable=False))
        batch_op.create_unique_constraint(
            'uq_extracted_phenotypes_paper_patient_phenotype_idx',
            ['paper_id', 'patient_idx', 'phenotype_idx'],
        )
        batch_op.drop_column('hpo_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hpo_reasoning')
        batch_op.drop_column('evidence_contexts')
        batch_op.drop_column('text')
        batch_op.drop_column('hpo_name')

    with op.batch_alter_table('extracted_variants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('created_at')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('last_modified')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pedigrees', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedigrees', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DATETIME(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DATETIME(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DATETIME(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('extracted_variants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DATETIME(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hpo_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(), nullable=False))
        batch_op.add_column(
            sa.Column('evidence_contexts', sqlite.JSON(), nullable=False)
        )
        batch_op.add_column(sa.Column('hpo_reasoning', sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DATETIME(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column('hpo_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            'uq_extracted_phenotypes_paper_patient_phenotype_idx', type_='unique'
        )
        batch_op.drop_column('concept_evidence')
        batch_op.drop_column('concept')
        batch_op.drop_column('phenotype_idx')

    # ### end Alembic commands ###
