"""change_enriched_variant_fk_to_variant_id

Revision ID: 5c7bee6d1043
Revises: 2c82db2f13fe
Create Date: 2026-05-19 00:15:33.881632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c7bee6d1043'
down_revision: Union[str, None] = '2c82db2f13fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('DELETE FROM enriched_variants')

    with op.batch_alter_table('enriched_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enriched_variants_harmonized_variant_id'))
        batch_op.drop_constraint(
            batch_op.f('uq_enriched_variants_harmonized_variant_id'), type_='unique'
        )
        batch_op.drop_column('harmonized_variant_id')
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.create_index(
            'ix_enriched_variants_variant_id', ['variant_id'], unique=False
        )
        batch_op.create_unique_constraint(
            'uq_enriched_variants_variant_id', ['variant_id']
        )
        batch_op.create_foreign_key(
            None, 'variants', ['variant_id'], ['id'], ondelete='CASCADE'
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enriched_variants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('harmonized_variant_id', sa.INTEGER(), nullable=False)
        )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            None,
            'harmonized_variants',
            ['harmonized_variant_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_constraint('uq_enriched_variants_variant_id', type_='unique')
        batch_op.drop_index('ix_enriched_variants_variant_id')
        batch_op.create_unique_constraint(
            batch_op.f('uq_enriched_variants_harmonized_variant_id'),
            ['harmonized_variant_id'],
        )
        batch_op.create_index(
            batch_op.f('ix_enriched_variants_harmonized_variant_id'),
            ['harmonized_variant_id'],
            unique=False,
        )
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
