"""add hpos table

Revision ID: 65bd823226af
Revises: 26e1efd53c70
Create Date: 2026-03-24 21:45:48.045833

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65bd823226af'
down_revision: Union[str, None] = '26e1efd53c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hpos',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('patient_idx', sa.Integer(), nullable=False),
        sa.Column('phenotype_idx', sa.Integer(), nullable=False),
        sa.Column('hpo_term', sa.JSON(), nullable=True),
        sa.Column('hpo_evidence', sa.JSON(), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['paper_id', 'patient_idx', 'phenotype_idx'],
            [
                'extracted_phenotypes.paper_id',
                'extracted_phenotypes.patient_idx',
                'extracted_phenotypes.phenotype_idx',
            ],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'paper_id',
            'patient_idx',
            'phenotype_idx',
            name='uq_hpos_paper_patient_phenotype',
        ),
    )
    with op.batch_alter_table('hpos', schema=None) as batch_op:
        batch_op.create_index('ix_hpos_paper_id', ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hpos', schema=None) as batch_op:
        batch_op.drop_index('ix_hpos_paper_id')

    op.drop_table('hpos')
    # ### end Alembic commands ###
