"""add de_novo field to patient_variant_links

Revision ID: 6c4eb1b68b03
Revises: 5c7bee6d1043
Create Date: 2026-05-19 21:48:38.473727

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c4eb1b68b03'
down_revision: Union[str, None] = '5c7bee6d1043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('de_novo', sa.Boolean(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column(
                'de_novo_evidence',
                sa.JSON(),
                nullable=False,
                server_default='{"value": false, "reasoning": "Not specified"}',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.drop_column('de_novo_evidence')
        batch_op.drop_column('de_novo')

    # ### end Alembic commands ###
