"""add_pedigree_descriptions_table

Revision ID: 7703c1005927
Revises: 01f89ca46c4c
Create Date: 2026-03-21 14:34:32.312102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7703c1005927'
down_revision: Union[str, None] = '01f89ca46c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pedigrees',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('paper_id'),
    )
    with op.batch_alter_table('pedigrees', schema=None) as batch_op:
        batch_op.create_index('ix_pedigrees_paper_id', ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedigrees', schema=None) as batch_op:
        batch_op.drop_index('ix_pedigrees_paper_id')

    op.drop_table('pedigrees')
    # ### end Alembic commands ###
