"""paper types non nullable

Revision ID: 8533660e269b
Revises: eb6bb798b30f
Create Date: 2026-03-05 19:47:56.169493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8533660e269b'
down_revision: Union[str, None] = 'eb6bb798b30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column(
            'paper_types', existing_type=sqlite.JSON(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('paper_types', existing_type=sqlite.JSON(), nullable=True)

    # ### end Alembic commands ###
