"""add old_value and new_value to edits

Revision ID: 9aa984af2f96
Revises: 32bc2c2d591b
Create Date: 2026-09-21 14:26:37.774891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9aa984af2f96'
down_revision: Union[str, None] = '32bc2c2d591b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')

    # ### end Alembic commands ###
