"""add patients table

Revision ID: a111864ea9d9
Revises: 8533660e269b
Create Date: 2026-03-18 15:07:44.481533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a111864ea9d9'
down_revision: Union[str, None] = '8533660e269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patients',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('patient_idx', sa.Integer(), nullable=False),
        sa.Column('identifier', sa.Text(), nullable=False),
        sa.Column('proband_status', sa.Text(), nullable=False),
        sa.Column('sex', sa.Text(), nullable=False),
        sa.Column('age_diagnosis', sa.Text(), nullable=True),
        sa.Column('age_report', sa.Text(), nullable=True),
        sa.Column('age_death', sa.Text(), nullable=True),
        sa.Column('country_of_origin', sa.Text(), nullable=False),
        sa.Column('race_ethnicity', sa.Text(), nullable=False),
        sa.Column('affected_status', sa.Text(), nullable=False),
        sa.Column('identifier_evidence_context', sa.Text(), nullable=True),
        sa.Column('proband_status_evidence_context', sa.Text(), nullable=True),
        sa.Column('sex_evidence_context', sa.Text(), nullable=True),
        sa.Column('age_diagnosis_evidence_context', sa.Text(), nullable=True),
        sa.Column('age_report_evidence_context', sa.Text(), nullable=True),
        sa.Column('age_death_evidence_context', sa.Text(), nullable=True),
        sa.Column('country_of_origin_evidence_context', sa.Text(), nullable=True),
        sa.Column('race_ethnicity_evidence_context', sa.Text(), nullable=True),
        sa.Column('affected_status_evidence_context', sa.Text(), nullable=True),
        sa.Column('identifier_reasoning', sa.Text(), nullable=True),
        sa.Column('proband_status_reasoning', sa.Text(), nullable=True),
        sa.Column('sex_reasoning', sa.Text(), nullable=True),
        sa.Column('age_diagnosis_reasoning', sa.Text(), nullable=True),
        sa.Column('age_report_reasoning', sa.Text(), nullable=True),
        sa.Column('age_death_reasoning', sa.Text(), nullable=True),
        sa.Column('country_of_origin_reasoning', sa.Text(), nullable=True),
        sa.Column('race_ethnicity_reasoning', sa.Text(), nullable=True),
        sa.Column('affected_status_reasoning', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'paper_id', 'patient_idx', name='uq_patients_paper_patient_idx'
        ),
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_paper_id', ['paper_id'], unique=False)
        batch_op.create_index(
            'ix_patients_paper_id_identifier', ['paper_id', 'identifier'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_paper_id_identifier')
        batch_op.drop_index('ix_patients_paper_id')

    op.drop_table('patients')
    # ### end Alembic commands ###
