"""add main_focus field to variants

Revision ID: a48bffd58432
Revises: c6f7ab602a6f
Create Date: 2026-04-02 15:33:15.979960

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a48bffd58432'
down_revision: Union[str, None] = 'c6f7ab602a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        # Step 1: add columns with temporary server defaults for existing rows
        batch_op.add_column(
            sa.Column(
                'main_focus',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),  # False
            )
        )
        batch_op.add_column(
            sa.Column(
                'main_focus_evidence',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'{}'"),  # empty JSON object
            )
        )

        # Step 2: remove server defaults for future inserts
        batch_op.alter_column('main_focus', server_default=None)
        batch_op.alter_column('main_focus_evidence', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('main_focus_evidence')
        batch_op.drop_column('main_focus')

    # ### end Alembic commands ###
