"""add patient_variant_links table

Revision ID: a96186acc8fb
Revises: 3226e581f26d
Create Date: 2026-03-03 14:34:50.563867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96186acc8fb'
down_revision: Union[str, Sequence[str], None] = '3226e581f26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_variant_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('zygosity', sa.String(), nullable=False),
    sa.Column('inheritance', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('evidence_context', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('linkage_notes', sa.Text(), nullable=False),
    sa.Column('testing_methods', sa.JSON(), nullable=True),
    sa.Column('testing_methods_evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_variant_links_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_variant_links_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_variant_links_variant_id'), ['variant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_variant_links_variant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_variant_links_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_variant_links_paper_id'))

    op.drop_table('patient_variant_links')
    # ### end Alembic commands ###
