"""add tasks started_at

Revision ID: acd4fb06fa44
Revises: 5767de58a19b
Create Date: 2026-09-13 13:43:01.548853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd4fb06fa44'
down_revision: Union[str, None] = '5767de58a19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Plain ADD COLUMN, not batch_alter_table. On SQLite batch mode copies the
    # table, drops the original and renames the copy -- and `tasks` both holds
    # ~9k rows on dev and carries a CASCADE foreign key to papers, which is the
    # shape that emptied the patients table in 3b2d941d02a2. SQLite does ADD
    # COLUMN in place, so the hazard never arises.
    #
    # Nullable with no backfill: existing rows genuinely have no start time, and
    # inventing one would put fabricated durations into the estimates this
    # column exists to produce. They are simply excluded until they next run.
    op.add_column(
        'tasks',
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'started_at')

    # ### end Alembic commands ###
