"""Add patient_variant_links table

Revision ID: add_patient_variant_links
Revises: add_enriched_variants
Create Date: 2026-03-25 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_patient_variant_links'
down_revision: Union[str, None] = 'add_enriched_variants'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patient_variant_links',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('patient_idx', sa.Integer(), nullable=False),
        sa.Column('variant_idx', sa.Integer(), nullable=False),
        sa.Column('zygosity', sa.String(), nullable=False),
        sa.Column('inheritance', sa.String(), nullable=False),
        sa.Column('zygosity_evidence', sa.JSON(), nullable=False),
        sa.Column('inheritance_evidence', sa.JSON(), nullable=False),
        sa.Column('testing_methods', sa.JSON(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('paper_id', 'patient_idx', 'variant_idx', name='uq_patient_variant_links_paper_patient_variant'),
    )
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.create_index('ix_patient_variant_links_paper_id', ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_variant_links', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_variant_links_paper_id')

    op.drop_table('patient_variant_links')
    # ### end Alembic commands ###
