"""Add enriched_variants table

Revision ID: add_enriched_variants
Revises: 79de34f70fec
Create Date: 2026-03-25 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_enriched_variants'
down_revision: Union[str, None] = '79de34f70fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'enriched_variants',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('variant_idx', sa.Integer(), nullable=False),
        sa.Column('pathogenicity', sa.String(), nullable=True),
        sa.Column('submissions', sa.Integer(), nullable=True),
        sa.Column('stars', sa.Integer(), nullable=True),
        sa.Column('exon', sa.String(), nullable=True),
        sa.Column('revel', sa.Float(), nullable=True),
        sa.Column('alphamissense_class', sa.String(), nullable=True),
        sa.Column('alphamissense_score', sa.Float(), nullable=True),
        sa.Column('spliceai', sa.JSON(), nullable=True),
        sa.Column('gnomad_style_coordinates', sa.String(), nullable=True),
        sa.Column('rsid', sa.String(), nullable=True),
        sa.Column('caid', sa.String(), nullable=True),
        sa.Column('gnomad_top_level_af', sa.Float(), nullable=True),
        sa.Column('gnomad_popmax_af', sa.Float(), nullable=True),
        sa.Column('gnomad_popmax_population', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(
            ['paper_id', 'variant_idx'],
            ['harmonized_variants.paper_id', 'harmonized_variants.variant_idx'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('paper_id', 'variant_idx', name='uq_enriched_variants_paper_variant_idx'),
    )
    with op.batch_alter_table('enriched_variants', schema=None) as batch_op:
        batch_op.create_index('ix_enriched_variants_paper_id', ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enriched_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_enriched_variants_paper_id')

    op.drop_table('enriched_variants')
    # ### end Alembic commands ###
