"""add_extracted_variants_table

Revision ID: b24f2aba6b49
Revises: 7703c1005927
Create Date: 2026-03-24 10:44:18.325531

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b24f2aba6b49'
down_revision: Union[str, None] = '7703c1005927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'extracted_variants',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('variant_idx', sa.Integer(), nullable=False),
        sa.Column('gene', sa.String(), nullable=False),
        sa.Column('transcript', sa.String(), nullable=True),
        sa.Column('protein_accession', sa.String(), nullable=True),
        sa.Column('genomic_accession', sa.String(), nullable=True),
        sa.Column('lrg_accession', sa.String(), nullable=True),
        sa.Column('gene_accession', sa.String(), nullable=True),
        sa.Column('genomic_coordinates', sa.String(), nullable=True),
        sa.Column('genome_build', sa.String(), nullable=True),
        sa.Column('rsid', sa.String(), nullable=True),
        sa.Column('caid', sa.String(), nullable=True),
        sa.Column('variant_evidence_context', sa.Text(), nullable=True),
        sa.Column('variant_reasoning', sa.Text(), nullable=True),
        sa.Column('hgvs_c', sa.String(), nullable=True),
        sa.Column('hgvs_c_evidence_context', sa.Text(), nullable=True),
        sa.Column('hgvs_c_evidence_reasoning', sa.Text(), nullable=True),
        sa.Column('hgvs_p', sa.String(), nullable=True),
        sa.Column('hgvs_p_evidence_context', sa.Text(), nullable=True),
        sa.Column('hgvs_p_evidence_reasoning', sa.Text(), nullable=True),
        sa.Column('hgvs_g', sa.String(), nullable=True),
        sa.Column('hgvs_g_evidence_context', sa.Text(), nullable=True),
        sa.Column('hgvs_g_evidence_reasoning', sa.Text(), nullable=True),
        sa.Column('variant_type', sa.String(), nullable=False),
        sa.Column('variant_type_evidence_context', sa.Text(), nullable=True),
        sa.Column('variant_type_reasoning', sa.Text(), nullable=True),
        sa.Column('functional_evidence', sa.Boolean(), nullable=False),
        sa.Column('functional_evidence_evidence_context', sa.Text(), nullable=True),
        sa.Column('functional_evidence_reasoning', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'paper_id', 'variant_idx', name='uq_extracted_variants_paper_variant_idx'
        ),
    )
    with op.batch_alter_table('extracted_variants', schema=None) as batch_op:
        batch_op.create_index(
            'ix_extracted_variants_paper_id', ['paper_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_extracted_variants_paper_id')

    op.drop_table('extracted_variants')
    # ### end Alembic commands ###
