"""add is_supplement to pedigrees

Revision ID: b7a96f15119d
Revises: 895928bdd7be
Create Date: 2026-09-29 01:36:51.249182

Hand-edited away from the autogenerated (empty) form. Plain ADD COLUMN, which
SQLite performs in place, and `pedigrees` has no CASCADE dependents -- see the
migration-safety section of CLAUDE.md and 24be132ecd9b for the same pattern.

image_id is namespaced separately per supplement/main (pdf_image_path takes a
supplement flag), so a pedigree sourced from a paper's supplement was
previously indistinguishable from one sourced from the main pipeline sharing
the same image_id -- the API always resolved the image as if it were from the
main pipeline. Every existing pedigrees row predates supplement support for
this field entirely, so backfilling false is correct for all of them.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a96f15119d'
down_revision: Union[str, None] = '895928bdd7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'pedigrees',
        sa.Column(
            'is_supplement',
            sa.Boolean(),
            server_default='0',
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column('pedigrees', 'is_supplement')
