"""add static_file_headers table

Revision ID: c380b63c7836
Revises: 6fcfd7578dae
Create Date: 2026-02-11 18:24:26.110446+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c380b63c7836'
down_revision: Union[str, Sequence[str], None] = '6fcfd7578dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_file_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_identifier', sa.String(), nullable=False),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('content_length', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_file_headers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_file_headers_file_identifier'), ['file_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_file_headers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_file_headers_file_identifier'))

    op.drop_table('static_file_headers')
    # ### end Alembic commands ###
