"""change_conversation_id_to_conversation_ids

Revision ID: c3e1ecc3aa06
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 11:32:31.672931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3e1ecc3aa06'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'conversation_ids', sa.JSON(), nullable=False, server_default='{}'
            )
        )
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('conversation_ids')

    # ### end Alembic commands ###
