"""rename hpo_reasoning to reasoning

Revision ID: c6f7ab602a6f
Revises: eb6bb798b30f
Create Date: 2026-03-26 15:40:49.933743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6f7ab602a6f'
down_revision: Union[str, None] = 'eb6bb798b30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hpos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.String(), nullable=False))
        batch_op.drop_column('hpo_reasoning')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hpos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hpo_reasoning', sa.String(), nullable=False))
        batch_op.drop_column('reasoning')

    # ### end Alembic commands ###
