"""add user notification preference and paper completion guard

Revision ID: cab7e60ebd9f
Revises: o5p6q7r8s9t0
Create Date: 2026-09-10 22:17:34.584886

Hand-edited away from the autogenerated form, which wrapped both changes in
batch_alter_table. On SQLite that copies the table, drops the original and
renames the copy -- and `papers` has CASCADE dependents (patients, variants,
tasks, patient_variant_occurrences), which is the exact shape that emptied the
patients table in migration 3b2d941d02a2. See the migration-safety section of
CLAUDE.md.

Batch mode is not needed here at all: both changes are plain ADD COLUMN, which
SQLite performs in place. Adding a NOT NULL column is legal because it carries a
server_default, which backfills existing rows. Using op.add_column sidesteps the
hazard rather than working around it with a PRAGMA.

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cab7e60ebd9f'
down_revision: Union[str, None] = 'o5p6q7r8s9t0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable: NULL means "not yet notified", which is correct for every
    # existing paper -- including already-completed ones, which must not
    # generate a burst of mail about work finished weeks ago. The worker only
    # notifies on the transition it observes itself.
    op.add_column(
        'papers',
        sa.Column('completion_notified_at', sa.DateTime(timezone=True), nullable=True),
    )
    # Opt-in. Existing users never asked to be emailed, so they default to off.
    op.add_column(
        'users',
        sa.Column(
            'notify_on_paper_complete',
            sa.Boolean(),
            server_default='0',
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column('users', 'notify_on_paper_complete')
    op.drop_column('papers', 'completion_notified_at')
