"""add age units to patients

Revision ID: d09d0a5680a8
Revises: c6f7ab602a6f
Create Date: 2026-04-03 11:38:53.904174

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd09d0a5680a8'
down_revision: Union[str, None] = 'eb6bb798b30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'age_diagnosis_unit',
                sa.Enum('Years', 'Months', 'Days', name='ageunit'),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                'age_report_unit',
                sa.Enum('Years', 'Months', 'Days', name='ageunit'),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                'age_death_unit',
                sa.Enum('Years', 'Months', 'Days', name='ageunit'),
                nullable=True,
            )
        )

    # ### end Alembic commands ###

    # Set all age units to 'Months' for existing data
    op.execute(
        "UPDATE patients SET age_diagnosis_unit = 'Months' WHERE age_diagnosis_unit IS NULL"
    )
    op.execute(
        "UPDATE patients SET age_report_unit = 'Months' WHERE age_report_unit IS NULL"
    )
    op.execute(
        "UPDATE patients SET age_death_unit = 'Months' WHERE age_death_unit IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('age_death_unit')
        batch_op.drop_column('age_report_unit')
        batch_op.drop_column('age_diagnosis_unit')

    # ### end Alembic commands ###
