"""add tasks table

Revision ID: d09d0a5680a8
Revises: c6f7ab602a6f
Create Date: 2026-04-04 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd09d0a5680a8'
down_revision: Union[str, None] = 'c6f7ab602a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'PDF Parsing',
                'Paper Metadata',
                'Variant Extraction',
                'Pedigree Description',
                'Patient Extraction',
                'Variant Harmonization',
                'Variant Enrichment',
                'Patient Variant Linking',
                'Phenotype Extraction',
                'HPO Linking',
                name='tasktype',
            ),
            nullable=False,
        ),
        sa.Column('patient_id', sa.Integer(), nullable=True),
        sa.Column('variant_id', sa.Integer(), nullable=True),
        sa.Column('phenotype_id', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('Pending', 'Running', 'Completed', 'Failed', name='taskstatus'),
            nullable=False,
        ),
        sa.Column('tries', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['phenotype_id'], ['phenotypes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_tasks_paper_id', 'tasks', ['paper_id'], unique=False)
    op.create_index('ix_tasks_patient_id', 'tasks', ['patient_id'], unique=False)
    op.create_index('ix_tasks_phenotype_id', 'tasks', ['phenotype_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_type', 'tasks', ['type'], unique=False)
    op.create_index('ix_tasks_variant_id', 'tasks', ['variant_id'], unique=False)
    op.create_index(
        'ix_tasks_paper_id_status', 'tasks', ['paper_id', 'status'], unique=False
    )
    op.create_index(
        'ix_tasks_dedup',
        'tasks',
        ['type', 'paper_id', 'patient_id', 'variant_id', 'phenotype_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_dedup', table_name='tasks')
    op.drop_index('ix_tasks_paper_id_status', table_name='tasks')
    op.drop_index('ix_tasks_variant_id', table_name='tasks')
    op.drop_index('ix_tasks_type', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_phenotype_id', table_name='tasks')
    op.drop_index('ix_tasks_patient_id', table_name='tasks')
    op.drop_index('ix_tasks_paper_id', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
