"""add_extracted_phenotypes_table

Revision ID: d5f3a9c2b1e4
Revises: c4e2f8a1b3d2
Create Date: 2026-03-24 13:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5f3a9c2b1e4'
down_revision: Union[str, None] = 'c4e2f8a1b3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'extracted_phenotypes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paper_id', sa.String(), nullable=False),
        sa.Column('patient_idx', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('negated', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('uncertain', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('family_history', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('evidence_contexts', sa.JSON(), nullable=False),
        sa.Column('onset', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('modifier', sa.String(), nullable=True),
        sa.Column('hpo_id', sa.String(), nullable=True),
        sa.Column('hpo_name', sa.String(), nullable=True),
        sa.Column('hpo_reasoning', sa.String(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.create_index(
            'ix_extracted_phenotypes_paper_id', ['paper_id'], unique=False
        )
        batch_op.create_index(
            'ix_extracted_phenotypes_paper_patient',
            ['paper_id', 'patient_idx'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_phenotypes', schema=None) as batch_op:
        batch_op.drop_index('ix_extracted_phenotypes_paper_patient')
        batch_op.drop_index('ix_extracted_phenotypes_paper_id')

    op.drop_table('extracted_phenotypes')
    # ### end Alembic commands ###
