"""remove pipeline_status column from papers table

Revision ID: e1f2g3h4i5j6
Revises: d09d0a5680a8
Create Date: 2026-04-04 10:05:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e1f2g3h4i5j6'
down_revision: Union[str, None] = 'd09d0a5680a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('ix_papers_pipeline_status')
        batch_op.drop_column('pipeline_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'pipeline_status',
                sa.VARCHAR(length=20),
                nullable=False,
                server_default='Queued',
            )
        )
        batch_op.create_index('ix_papers_pipeline_status', ['pipeline_status'])

    # ### end Alembic commands ###
