from pathlib import Path

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext

from lib.api import db
from lib.models import Base


def test_alembic_upgrade_head(monkeypatch, tmp_path):
    """Simple test that all migrations apply cleanly on a fresh DB."""

    monkeypatch.setattr(db.env, 'CAA_ROOT', str(tmp_path))
    monkeypatch.setattr(db.env, 'SQLLITE_DIR', '')
    monkeypatch.setattr(db, '_engine', None)
    monkeypatch.setattr(db, '_session_factory', None)

    repo_root = Path(__file__).resolve().parents[2]
    cfg = Config(str(repo_root / 'alembic.ini'))
    command.upgrade(cfg, 'head')

    # Validate that the supplied migrations in migratios/versions correspond to the schema
    # generated by Base.metadata.create_all()
    #
    # To generate a new migration with the reflected updates, run `uv run alembic revision --autogenerate`
    # (with `./bin/api` running, as the command references your local database).
    engine = db.get_engine()
    diffs = compare_metadata(
        MigrationContext.configure(engine.connect()), Base.metadata
    )
    assert diffs == []
